### PR TITLE
The angular schema form update saga continued

### PR DESCRIPTION
**Pull request by bluemaex**
Updates the implementation to comply with all the changes angular-schema-form introduced in 0.8

 * update decorators which have been completely changed including logic, which caused most of our errors
 * Removing our own sf-invalidator to use the new custom validation scheme. 
 * Update ConstraintMerger to support nested forms, so we pass the correct form definition
 * Update not-blank constraint to use 'default' and '302' validationMessage-namespace

Well, and probably more. :scream:

### CODE REVIEW

**Comment by lsd** [comment]
@bluemaex is OK with me reviewing this early tomm since I'm working on other tickets atm. Just putting a note here that this hasn't slipped past my radar

**Comment by lsd** [comment]
@bluemaex works overall but assignment.code.length.min translation working (shows 'assignment.code.length.min') - did this change?

**Comment by bluemaex** [comment]
no, not that I know of. It works here on my machine. maybe you try a console cache:clear, that usually helps for me when I have the problem.

**Comment by bluemaex** [comment]
@lsd ping

**Pull request merged**
