### PR TITLE
manually set the view value on select2's change event

### PR DESCRIPTION
**Pull request by rwos**
Why is that needed now, and why worked it without it before? No idea.
But it does work.

### CODE REVIEW

**Comment by rwos** [comment]
@cameronprattedwards here are more things that I don't know
* why that test doesn't work
* how to trigger a change in such a way that it matches what happens when you come via the browser

I've now skipped that test. I have a slight feeling that this thing will come back to haunt us sooner or later.

**Comment by cameronprattedwards** [comment]
Hrm. I think I might be able to debug that. Please hold.

**Comment by cameronprattedwards** [comment]
@rwos I just added a conditional to check to see if the user is actually adding something. It passes the tests and the functionality still works - I think this was breaking because a value doesn't always get added, such as when selecting the default option. If you approve, I'll assign this to someone else to merge.

**Comment by cameronprattedwards** [comment]
As @rwos is probably home for the day, I'm just going to go ahead and assign this to @littlebigbot.

**Comment by cameronprattedwards** [comment]
@marsch This PR should fix the problems you've been facing as well.

**Comment by rwos** [comment]
@cameronprattedwards :+1: thanks!

**Pull request merged**
